### ISSUE TITLE
Issues with st2auth with pam authentication /w Centos

### ISSUE THREAD

**Issue by jonahadmin** [StackStorm/st2-auth-backend-pam#11]
I just wanted to document my trials and tribulations with getting pam authentication working on ST2 on Centos 7:

* Prior to installing the module, I installed libpam0g, which on Centos is located in the pam-devel package.
* I then installed the package via ```/opt/stackstorm/st2/bin/pip install git+https://github.com/StackStorm/st2-auth-backend-pam.git@master#egg=st2_auth_backend_pam```
* I then replaced the [auth] section with the configuration example provided in readme.md, adjusting ```cert```, ```key``` to point to my certificate files, and ```api_url``` to refer to the st2 host.
* I adjusted the logging file to point to /etc/st2/st2auth.logging.conf
* I ended up being unable to launch st2auth.  Without detailing all the digging I did, I discovered the following:
  * For PAM to work, I needed to update /lib/systemd/system/st2auth.service to load st2auth as the root user, which is apparently required for the PAM integration to work properly.
  * The log file specified in the readme.md doesn't actually exist.  The correct filename is ```/etc/st2/logging.auth.conf```
/opt/stackstorm/st2/bin/st2auth --config-file /etc/st2/st2.conf

**Comment by jonahadmin** [comment]
Is there no alternative to running st2auth as root?  Is it because it's accessing the login PAM service?

For example, Postgres is able to use PAM authentication, and I was able to accomplish that by creating a dedicated PAM service for it.

**Comment by LindsayHill** [comment]
I changed the logging configuration file example path in the README https://github.com/StackStorm/st2-auth-backend-pam/pull/12
